### ISSUE TITLE
Only one browser papears when I choose a browser to backup.

### ISSUE THREAD

**Issue by soraup** [Nikola-K/RESTool#23]
Hi, Im using Safari on OS Yosemite, and suddenly I can't choose between my browsers, now only Chrome appears, but not safari at all which is my main one. How can I fix this? 
I restarted my computer, opened and closed my browsers to see if that would solve the issue but nothing. Please help!!
![screen shot 2015-08-16 at 3 17 45 pm](https://cloud.githubusercontent.com/assets/13823115/9295172/09e4f364-442a-11e5-8c61-a9eb6a1c419b.png)

**Comment by Nikola-K** [comment]
Hi, could you do these steps please:

1. Find the location of the settings file manually - it should be in the location described here: https://www.reddit.com/r/Enhancement/wiki/backing_up_res_settings#wiki_safari

2. If the file does indeed exist in the location specified in the first step, enable debugging and submit the log file: https://github.com/Nikola-K/RESTool#how-to-report-issues

If the file exists in a different location please let me know what it is and I'll look into it.

**Comment by Nikola-K** [comment]
Closed due to lack of information.
