### ISSUE TITLE
Sync doesn't seem to work Chrome Win7 -> Chrome Win8

### ISSUE THREAD

**Issue by loopuleasa** [Nikola-K/RESTool#26]
I used dropbox to sync the program & the backup file for my work computer and I did restore backup to first server multiple times.

![image](https://cloud.githubusercontent.com/assets/5671120/10302696/1ebdf3ac-6c17-11e5-9007-383d9bd02c2a.png)

It still doesn't work.

I had chrome shut down, and it  still told me the message "Please ensure chrome is closed" or something.

I am unsure what isn't working.

**Comment by Nikola-K** [comment]
Chrome sometimes ends up running in the background and changing extension data then leads to the file not being written properly - or more accurately chrome overwriting it soon-ish. Do you see it running when you open task manager?

**Comment by loopuleasa** [comment]
There we go, there were some processes in the background.
Shit chrome does.

**Comment by loopuleasa** [comment]
Btw, you're a boss and you should join the RES team

Syncing is the only thing the whole shebang was missing, and you saved me time (after about 10 RES data losses and only sticking to default)

Thanks.

**Comment by Nikola-K** [comment]
Thanks, I really appreciate it! I'm glad it helped and worked as expected!
