### ISSUE TITLE
Support for Chrome Canary?

### ISSUE THREAD

**Issue by totalcereal** [Nikola-K/RESTool#9]
I enjoy using the development version of Chrome, Canary, but importing my RES settings into Canary is a pain. Since the tool supports the dev version of Firefox, why not Chrome as well?

**Comment by Nikola-K** [comment]
I'll install it tonight and if there are no major changes necessary from the Chrome module it'll be added to the next version milestone https://github.com/Nikola-K/RESTool/milestones/Version%200.2
